name: ci
on:
  push:
    branches: main
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    uses: ./.github/workflows/pr.yml
  doc:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.publish-docs.outputs.page_url }}
    steps:
      - name: Publish documentation
        id: publish-docs
        uses: actions/deploy-pages@v4
