name: ci
on:
  pull_request:
  workflow_call:

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: rustup show
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Test
        run: cargo test --all-features --workspace
      - name: Lint
        run: cargo clippy --all-features --no-deps --workspace
      - name: Build documentation
        run: cargo doc --all-features --no-deps --workspace
      - name: Copy assets
        run: |
          cat << EOF > target/doc/index.html
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url='samples/index.html'" />
            </head>
          </head>
          EOF
          cp -r docs/assets/ target/doc/
      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc/
